# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Card.destroy_all
User.destroy_all
Card.create(name: "Ace of Spades", value: "1,11", pic: "/assets/AS.png")
Card.create(name: "Two of Spades", value: "2", pic: "/assets/2S.png")
Card.create(name: "Three of Spades", value: "3", pic: "/assets/3S.png")
Card.create(name: "Four of Spades", value: "4", pic: "/assets/4S.png")
Card.create(name: "Five of Spades", value: "5", pic: "/assets/5S.png")
Card.create(name: "Six of Spades", value: "6", pic: "/assets/6S.png")
Card.create(name: "Seven of Spades", value: "7", pic: "/assets/7S.png")
Card.create(name: "Eight of Spades", value: "8", pic: "/assets/8S.png")
Card.create(name: "Nine of Spades", value: "9", pic: "/assets/9S.png")
Card.create(name: "Ten of Spades", value: "10", pic: "/assets/10S.png")
Card.create(name: "Jack of Spades", value: "10", pic: "/assets/JS.png")
Card.create(name: "Queen of Spades", value: "10", pic: "/assets/QS.png")
Card.create(name: "King of Spades", value: "10", pic: "/assets/KS.png")
Card.create(name: "Ace of Diamonds", value: "1,11", pic: "/assets/AD.png")
Card.create(name: "Two of Diamonds", value: "2", pic: "/assets/2D.png")
Card.create(name: "Three of Diamonds", value: "3", pic: "/assets/3D.png")
Card.create(name: "Four of Diamonds", value: "4", pic: "/assets/4D.png")
Card.create(name: "Five of Diamonds", value: "5", pic: "/assets/5D.png")
Card.create(name: "Six of Diamonds", value: "6", pic: "/assets/6D.png")
Card.create(name: "Seven of Diamonds", value: "7", pic: "/assets/7D.png")
Card.create(name: "Eight of Diamonds", value: "8", pic: "/assets/8D.png")
Card.create(name: "Nine of Diamonds", value: "9", pic: "/assets/9D.png")
Card.create(name: "Ten of Diamonds", value: "10", pic: "/assets/10D.png")
Card.create(name: "Jack of Diamonds", value: "10", pic: "/assets/JD.png")
Card.create(name: "Queen of Diamonds", value: "10", pic: "/assets/QD.png")
Card.create(name: "King of Diamonds", value: "10", pic: "/assets/KD.png")
Card.create(name: "Ace of Hearts", value: "1,11", pic: "/assets/AH.png")
Card.create(name: "Two of Hearts", value: "2", pic: "/assets/2H.png")
Card.create(name: "Three of Hearts", value: "3", pic: "/assets/3H.png")
Card.create(name: "Four of Hearts", value: "4", pic: "/assets/4H.png")
Card.create(name: "Five of Hearts", value: "5", pic: "/assets/5H.png")
Card.create(name: "Six of Hearts", value: "6", pic: "/assets/6H.png")
Card.create(name: "Seven of Hearts", value: "7", pic: "/assets/7H.png")
Card.create(name: "Eight of Hearts", value: "8", pic: "/assets/8H.png")
Card.create(name: "Nine of Hearts", value: "9", pic: "/assets/9H.png")
Card.create(name: "Ten of Hearts", value: "10", pic: "/assets/10H.png")
Card.create(name: "Jack of Hearts", value: "10", pic: "/assets/JH.png")
Card.create(name: "Queen of Hearts", value: "10", pic: "/assets/QH.png")
Card.create(name: "King of Hearts", value: "10", pic: "/assets/KH.png")
Card.create(name: "Ace of Clubs", value: "1,11", pic: "/assets/AC.png")
Card.create(name: "Two of Clubs", value: "2", pic: "/assets/2C.png")
Card.create(name: "Three of Clubs", value: "3", pic: "/assets/3C.png")
Card.create(name: "Four of Clubs", value: "4", pic: "/assets/4C.png")
Card.create(name: "Five of Clubs", value: "5", pic: "/assets/5C.png")
Card.create(name: "Six of Clubs", value: "6", pic: "/assets/6C.png")
Card.create(name: "Seven of Clubs", value: "7", pic: "/assets/7C.png")
Card.create(name: "Eight of Clubs", value: "8", pic: "/assets/8C.png")
Card.create(name: "Nine of Clubs", value: "9", pic: "/assets/9C.png")
Card.create(name: "Ten of Clubs", value: "10", pic: "/assets/10C.png")
Card.create(name: "Jack of Clubs", value: "10", pic: "/assets/JC.png")
Card.create(name: "Queen of Clubs", value: "10", pic: "/assets/QC.png")
Card.create(name: "King of Clubs", value: "10", pic: "/assets/KC.png")

philip = User.create(name: "Philip",money: 500)
michael = User.create(name: "Michael", money: 500)
karen = User.create(name: "Karen", money: 500)
claire = User.create(name: "Claire", money: 500)

